### ISSUE TITLE
TypeError: Body is unusable

### ISSUE THREAD

**Issue by floydspace** [Effect-TS/platform#226]
Following error occurs in line https://github.com/Effect-TS/platform/blob/713dc1130cf0749ad45dd31d5a045f609abc933c/packages/platform/src/internal/http/clientResponse.ts#L79 when running `json` or `text` getter twice
```
_
TypeError: Body is unusable
    at specConsumeBody (node:internal/deps/undici/undici:6630:15)
    at Response.text (node:internal/deps/undici/undici:6530:18)
    at try (.../node_modules/.pnpm/@effect+platform@0.25.1_@effect+schema@0.46.1_effect@2.0.0-next.52/node_modules/@effect/platform/dist/clientResponse-b269ed37.cjs.dev.js:82:30)
    at EffectPrimitive.i0 (.../node_modules/.pnpm/effect@2.0.0-next.52/node_modules/effect/dist/core-effect-02a7f1d7.cjs.dev.js:95:14)
    at FiberRuntime.Sync (.../node_modules/.pnpm/effect@2.0.0-next.52/node_modules/effect/dist/fiberRuntime-976a3e6f.cjs.dev.js:1752:22)
    at .../node_modules/.pnpm/effect@2.0.0-next.52/node_modules/effect/dist/fiberRuntime-976a3e6f.cjs.dev.js:1977:28
    at Object.context (.../node_modules/.pnpm/effect@2.0.0-next.52/node_modules/effect/dist/core-a0828fef.cjs.dev.js:1551:17)
    at FiberRuntime.runLoop (.../node_modules/.pnpm/effect@2.0.0-next.52/node_modules/effect/dist/fiberRuntime-976a3e6f.cjs.dev.js:1975:28)
    at FiberRuntime.evaluateEffect (.../node_modules/.pnpm/effect@2.0.0-next.52/node_modules/effect/dist/fiberRuntime-976a3e6f.cjs.dev.js:1572:29)
    at FiberRuntime.evaluateMessageWhileSuspended (.../node_modules/.pnpm/effect@2.0.0-next.52/node_modules/effect/dist/fiberRuntime-976a3e6f.cjs.dev.js:1545:16)
    at FiberRuntime.drainQueueOnCurrentThread (.../node_modules/.pnpm/effect@2.0.0-next.52/node_modules/effect/dist/fiberRuntime-976a3e6f.cjs.dev.js:1315:85)
    at Array.run (.../node_modules/.pnpm/effect@2.0.0-next.52/node_modules/effect/dist/fiberRuntime-976a3e6f.cjs.dev.js:1999:10)
    at MixedScheduler.starveInternal (.../node_modules/.pnpm/effect@2.0.0-next.52/node_modules/effect/Scheduler/dist/effect-Scheduler.cjs.dev.js:119:17)
    at .../node_modules/.pnpm/effect@2.0.0-next.52/node_modules/effect/Scheduler/dist/effect-Scheduler.cjs.dev.js:136:47
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {stack: 'TypeError: Body is unusable
    at specConsum…ions (node:internal/process/task_queues:95:5)', message: 'Body is unusable'}
```
For instance I need to print response before parsing body:
```ts
      pipe(
        Http.request.post(`UsersService/GetAccounts`),
        Http.request.jsonBody({}),
        Effect.flatMap(client),
        Effect.tap((res) =>
          Effect.flatMap(res.json, (json) =>
            Logger.logDebug("GetAccounts response", { json }),
          ),
        ),
        Effect.flatMap(Http.response.schemaBodyJson(GetAccountsResponse)),
      ),
```
Should we maybe cache the result, so getter could have "pure" behaviour?
Or define another reason for the error?

**Comment by tim-smart** [comment]
Should be addressed in the latest release.
